---
# # Rôle : passwords

# ## Description
# Ce rôle configure une politique de mots de passe renforcée à l'aide du module PAM **libpam-pwquality**. Il permet de garantir que les mots de passe répondent à des exigences de sécurité strictes.

# ## Références aux benchmarks de sécurité :
# 1. **CIS (Center for Internet Security)**
#    - **Recommandation 6.3.1** : Configurer des politiques de mots de passe renforcées.
#    - **Recommandation 6.3.2** : Vérifier la conformité de la politique.
#    - [Lien direct vers CIS Benchmarks](https://downloads.cisecurity.org/#/) *(Connexion requise)*

# 2. **ANSSI (Agence Nationale de la Sécurité des Systèmes d'Information)**
#    - **Recommandation R37** : Appliquer une politique stricte pour les mots de passe.
#    - [Lien direct vers ANSSI R37](https://www.ssi.gouv.fr/uploads/IMG/pdf/anssi-guide_linux.pdf) *(Page 42)*

# 3. **NIS 2 Directive**
#    - Exiger des politiques robustes pour protéger les systèmes critiques.

# ## Fonctionnalités :
# - Installation de `libpam-pwquality`.
# - Configuration des politiques de mots de passe dans `/etc/security/pwquality.conf`.
# - Vérification de la conformité avec les recommandations.

# ## Variables configurables :
# - `password_policy.minlen` : Longueur minimale des mots de passe.
# - `password_policy.minclass` : Nombre minimum de classes de caractères (majuscules, chiffres, caractères spéciaux, minuscules).

# # ## Notes :
# - Le fichier `/etc/security/pwquality.conf` est entièrement géré par Ansible.
# - Le commentaire `{{ ansible_managed }}` est ajouté au début du fichier pour indiquer qu'il est sous gestion d'Ansible.
# - Toute modification manuelle sera remplacée lors des exécutions futures d'Ansible.


---
# Installer libpam-pwquality pour gérer la politique de mots de passe
- name: Installer libpam-pwquality
  ansible.builtin.package:
    name: libpam-pwquality
    state: present
  tags:
    - passwords
    - installation

# Configurer la politique de mots de passe avec libpam-pwquality
- name: Configurer la politique de mots de passe
  ansible.builtin.copy:
    dest: /etc/security/pwquality.conf
    content: |
      # {{ ansible_managed }}
      # Politique renforcée des mots de passe
      minlen = {{ password_policy.minlen }}
      minclass = {{ password_policy.minclass }}
    mode: "0644"
    owner: root
    group: root
  tags:
    - passwords
    - security

# Vérifier la politique de mots de passe
- name: Vérifier la politique de mots de passe
  ansible.builtin.command:
    cmd: grep -E "minlen|minclass" /etc/security/pwquality.conf
    register: pwquality_check
    changed_when: false
  tags:
    - validation
