---
# Nombre de tentatives avant de bloquer l'utilisateur
pam_faillock_deny: 5

# Durée de blocage de l'utilisateur en secondes
pam_faillock_unlock_time: 900  # 15 minutes

# Durée entre chaque tentative de connexion en secondes
pam_faillock_fail_interval: 300  # 5 minutes
