---
# Rôle : kernel
#
# ## Description
# Ce rôle applique des paramètres sysctl pour durcir le noyau Linux et améliorer la sécurité du système.
# Il désactive également les protocoles inutilisés en blacklistant les modules correspondants.
#
# ## Références aux benchmarks de sécurité :
# 1. **CIS (Center for Internet Security)**
#    - **Recommandation 3.1** : Configurer les paramètres sysctl pour renforcer la sécurité du noyau.
#    - **Recommandation 3.5** : Désactiver les protocoles inutilisés (DCCP, SCTP, RDS, TIPC).
#    - [Lien direct vers CIS Benchmarks](https://downloads.cisecurity.org/#/) *(Connexion requise)*
#
# 2. **ANSSI (Agence Nationale de la Sécurité des Systèmes d'Information)**
#    - **Recommandation R17** : Appliquer des paramètres sysctl pour bloquer les attaques réseau courantes.
#    - **Recommandation R23** : Désactiver les modules inutilisés pour réduire la surface d'attaque.
#    - [Lien direct vers ANSSI](https://www.ssi.gouv.fr/uploads/IMG/pdf/anssi-guide_linux.pdf) *(Page 35)*
#
# ## Fonctionnalités :
# - Configuration des paramètres sysctl persistants dans `/etc/sysctl.d/99-hardening.conf`.
# - Application immédiate des paramètres sysctl.
# - Désactivation des protocoles inutilisés via le blacklistage de leurs modules.
#
# ## Variables configurables :
# - `sysctl_params` : Liste des paramètres sysctl à appliquer, avec leurs noms et valeurs.
# - `kernel_blacklist_modules` : Liste des modules noyau à blacklister.

# Configurer et rendre les paramètres sysctl persistants
- name: Configurer et rendre les paramètres sysctl persistants
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-hardening.conf
    content: |
      # {{ ansible_managed }}
      {% for param in sysctl_params %}
      {{ param.name }} = {{ param.value }}
      {% endfor %}
    mode: "0644"
  notify: Recharger sysctl
  tags:
    - kernel
    - security

# Vérifier que les paramètres sysctl sont appliqués
- name: Vérifier que les paramètres sysctl sont appliqués
  ansible.builtin.shell: "sysctl -n {{ item.name }}"
  register: sysctl_check
  changed_when: false
  loop: "{{ sysctl_params }}"
  tags:
    - kernel
    - validation

# Afficher les résultats de validation sysctl
- name: Afficher les résultats de validation sysctl
  debug:
    msg: >
      Paramètre {{ item.item.name }} attendu : {{ item.item.value }},
      actuel : {{ item.stdout }}
  loop: "{{ sysctl_check.results }}"
  when: item.stdout != item.item.value
  tags:
    - kernel
    - validation

# Blacklister les modules inutilisés
- name: Blacklister les modules inutilisés
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist.conf
    line: "blacklist {{ item }}"
    create: yes
  loop: "{{ kernel_blacklist_modules }}"
  tags:
    - kernel
    - hardening

# Blacklister les systèmes de fichiers inutiles
- name: Blacklister les systèmes de fichiers inutiles
  ansible.builtin.lineinfile:
    path: /etc/modprobe.d/blacklist-filesystems.conf
    line: "blacklist {{ item }}"
    create: yes
  loop: "{{ kernel_blacklist_filesystems }}"
  tags:
    - kernel
    - hardening
    - filesystem

# Installer AppArmor
- name: Installer AppArmor et ses utilitaires
  ansible.builtin.package:
    name:
      - apparmor
      - apparmor-utils
    state: present
  tags:
    - kernel
    - apparmor
    - installation

# Activer AppArmor
- name: Activer AppArmor
  ansible.builtin.service:
    name: apparmor
    state: started
    enabled: true
  tags:
    - kernel
    - apparmor
    - activation
