---
# # Rôle : post_deployment_report

# ## Description
# Ce rôle génère un rapport post-déploiement qui récapitule les journaux d'audit, l'état des services, et la configuration du pare-feu. Cela permet de garantir une transparence et une traçabilité après chaque exécution.

# ## Fonctionnalités
# - Crée un répertoire pour stocker les rapports post-déploiement.
# - Génère un rapport organisé avec des sections définies.
# - Applique des permissions strictes pour sécuriser le rapport.

# ## Variables configurables
# - `post_deployment_log_dir` : Répertoire où les rapports sont stockés.
# - `post_deployment_report_file` : Nom du fichier de rapport.
# - `audit_log_file` : Fichier d'audit à inclure dans la section "Audits".
# - `services_check_command` : Commande pour répertorier les services actifs.
# - `firewall_check_command` : Commande pour afficher l'état du pare-feu.
# - `report_sections` : Liste des sections à inclure dans le rapport (par exemple : "Audits", "Services", "Firewall").

# ## Exemple de variables
# ```yaml
# post_deployment_log_dir: "/var/log/post_deployment"
# post_deployment_report_file: "post_deployment_report.log"
# audit_log_file: "/var/log/audit_execution.log"
# services_check_command: "systemctl list-units --type=service --state=running"
# firewall_check_command: "ufw status verbose"
# report_sections:
#   - "Audits"
#   - "Services"
#   - "Firewall"

# Créer le répertoire de stockage des logs post-déploiement
- name: Créer le répertoire de logs post-déploiement
  file:
    path: "{{ post_deployment_log_dir }}"
    state: directory
    owner: root
    group: root
    mode: "0755"
  tags:
    - reporting
    - security

# Générer le rapport post-déploiement
- name: Générer un rapport post-déploiement
  shell: |
    echo "==== Rapport post-déploiement ====" > "{{ post_deployment_log_dir }}/{{ post_deployment_report_file }}"

    {% for section in report_sections %}
    echo "== {{ section }} ==" >> "{{ post_deployment_log_dir }}/{{ post_deployment_report_file }}"
    {% if section == 'Audits' %}
    tail -n 10 {{ audit_log_file }} >> "{{ post_deployment_log_dir }}/{{ post_deployment_report_file }}"
    {% elif section == 'Services' %}
    {{ services_check_command }} >> "{{ post_deployment_log_dir }}/{{ post_deployment_report_file }}"
    {% elif section == 'Firewall' %}
    {{ firewall_check_command }} >> "{{ post_deployment_log_dir }}/{{ post_deployment_report_file }}"
    {% endif %}
    {% endfor %}
  tags:
    - reporting
    - validation

# Restreindre les permissions du rapport
- name: Restreindre les permissions du rapport
  file:
    path: "{{ post_deployment_log_dir }}/{{ post_deployment_report_file }}"
