# Liste des paramètres sysctl à appliquer
sysctl_params:
  - { name: "net.ipv4.icmp_echo_ignore_all", value: "1" }
  - { name: "net.ipv4.tcp_syncookies", value: "1" }
  - { name: "net.ipv4.ip_forward", value: "0" }
  - { name: "net.ipv4.conf.all.send_redirects", value: "0" }
  - { name: "net.ipv4.conf.default.send_redirects", value: "0" }
  - { name: "net.ipv4.icmp_echo_ignore_broadcasts", value: "1" }
  - { name: "net.ipv4.conf.all.accept_source_route", value: "0" }
  - { name: "net.ipv6.conf.all.disable_ipv6", value: "1" }
  - { name: "net.ipv6.conf.default.disable_ipv6", value: "1" }

# Liste des modules noyau à blacklister
kernel_blacklist_modules:
  - dccp
  - sctp
  - rds
  - tipc

# Liste des systèmes de fichiers à blacklister
kernel_blacklist_filesystems:
  - cramfs
  - freevxfs
  - jffs2
  - hfs
  - hfsplus
  - squashfs
  - udf

# Liste des modules USB à blacklister (par défaut désactivé)
kernel_blacklist_usb_storage: true  # Choisissez true pour activer le blacklistage du module usb_storage
