---
# Rôle : grub-password
#
# ## Description
# Ce rôle configure un mot de passe sécurisé pour GRUB afin de limiter l'accès non autorisé aux options de démarrage critiques.
#
# ## Références aux benchmarks de sécurité :
# 1. **CIS (Center for Internet Security)**
#    - **Recommandation 1.5.3** : Configurer un mot de passe GRUB pour sécuriser les options de démarrage.
#
# 2. **ANSSI (Agence Nationale de la Sécurité des Systèmes d'Information)**
#    - **Recommandation R24** : Sécuriser l'accès au bootloader pour éviter des modifications non autorisées.
#
# ## Fonctionnalités :
# - Configuration d'un mot de passe GRUB à l'aide du fichier `/etc/grub.d/01_password`.
# - Utilisation d'Ansible Vault pour protéger le mot de passe sensible.
# - Mise à jour automatique de GRUB si le fichier de configuration est modifié.

- name: Vérifier si le fichier de mot de passe GRUB existe
  ansible.builtin.stat:
    path: "/etc/grub.d/01_password"
  register: grub_password_file_stat
  tags:
    - grub
    - security

- name: Installer les paquets Grub nécessaires
  ansible.builtin.package:
    name: >-
      {{ ['grub-common', 'grub-pc-bin'] + (['grub-firmware-riscv64'] if grub_firmware_issues | default(false) else []) }}
    state: present
  tags:
    - grub
    - installation

- name: Créer le fichier de configuration GRUB avec un mot de passe
  ansible.builtin.copy:
    dest: "/etc/grub.d/01_password"
    mode: "0755"
    owner: root
    group: root
    content: |
      #!/bin/sh
      set -e

      cat << 'EOF'
      set superusers="admin"
      password_pbkdf2 admin {{ vault_grub_password }}
      EOF
  notify: Update GRUB
  tags:
    - grub
    - security
