---
# Rôle : kernel
#
# ## Description
# Ce rôle applique des paramètres sysctl pour durcir le noyau Linux et améliorer la sécurité du système.
# Les paramètres sysctl configurent divers aspects de la pile réseau, de la gestion des paquets et d'autres fonctionnalités système.
#
# ## Références aux benchmarks de sécurité :
# 1. **CIS (Center for Internet Security)**
#    - **Recommandation 3.1** : Configurer les paramètres sysctl pour renforcer la sécurité du noyau.
#    - [Lien direct vers CIS Benchmarks](https://downloads.cisecurity.org/#/) *(Connexion requise)*
#
# 2. **ANSSI (Agence Nationale de la Sécurité des Systèmes d'Information)**
#    - **Recommandation R17** : Appliquer des paramètres sysctl pour bloquer les attaques réseau courantes.
#    - [Lien direct vers ANSSI R17](https://www.ssi.gouv.fr/uploads/IMG/pdf/anssi-guide_linux.pdf) *(Page 35)*
#
# ## Fonctionnalités :
# - Configuration des paramètres sysctl persistants dans `/etc/sysctl.d/99-hardening.conf`.
# - Application immédiate des paramètres sysctl.
#
# ## Variables configurables :
# - `sysctl_params` : Liste des paramètres sysctl à appliquer, avec leurs noms et valeurs.

- name: Configurer et rendre les paramètres sysctl persistants
  ansible.builtin.copy:
    dest: /etc/sysctl.d/99-hardening.conf
    content: |
      # {{ ansible_managed }}
      {% for param in sysctl_params %}
      {{ param.name }} = {{ param.value }}
      {% endfor %}
    mode: "0644"
  notify: Recharger sysctl
  tags:
    - kernel
    - security


- name: Vérifier que les paramètres sysctl sont appliqués
  ansible.builtin.shell: "sysctl -n {{ item.name }}"
  register: sysctl_check
  changed_when: false
  with_items: "{{ sysctl_params }}"
  tags:
    - kernel
    - validation

- name: Afficher les résultats de validation sysctl
  debug:
    msg: >
      Paramètre {{ item.item.name }} attendu : {{ item.item.value }},
      actuel : {{ item.stdout }}
  with_items: "{{ sysctl_check.results }}"
  when: item.stdout != item.item.value
  tags:
    - kernel
    - validation
