---
ssh_allowed_group: "sshusers"  # Groupe des utilisateurs autorisés à se connecter via SSH
ssh_allowed_users: []

ssh_config:
  # Empêcher la connexion root via SSH
  permit_root_login: "no"  # Désactive la connexion root via SSH (CIS 5.2.1, ANSSI R23)

  # Utiliser uniquement SSH version 2 pour plus de sécurité
  protocol: "2"  # Utilise uniquement SSH version 2 (CIS 5.1.1, ANSSI R22)

  # Limiter l'accès aux membres du groupe "sshusers"
  allow_groups: "sshusers"  # Autoriser uniquement les utilisateurs du groupe "sshusers" à se connecter

  # Empêcher les connexions par mot de passe et forcer l'usage des clés SSH
  passwordauthentication: "no"  # Désactive l'authentification par mot de passe (CIS 5.4.1)

  # Désactiver l'authentification par GSSAPI (si non utilisée)
  gssapi_authentication: "no"  # Désactive l'authentification GSSAPI

  # Désactiver le forwarding X11 pour éviter les risques liés aux tunnels
  x11_forwarding: "no"  # Désactive la redirection X11 via SSH (réduit les risques de tunneling)

  # Désactiver le tunneling TCP (port forwarding)
  AllowTcpForwarding: "no"  # Désactive la redirection de ports via SSH (empêche les utilisateurs de créer des tunnels TCP)

  # Désactiver le tunneling VPN via SSH (utilisation de "ssh -w")
  PermitTunnel: "no"  # Empêche l'utilisation de SSH pour créer des tunnels de type VPN

  # Paramètres pour garder la session SSH active et éviter les connexions inactives
  client_alive_interval: 300  # Envoie un paquet "keep-alive" toutes les 5 minutes
  client_alive_count_max: 3  # Nombre de tentatives de "keep-alive" avant de fermer la connexion

  # Limite le nombre de tentatives d'authentification échouées avant de fermer la connexion
  maxauthtries: 3  # Limite le nombre de tentatives d'authentification échouées avant de couper la connexion
