---
- name: Vérifier si Lynis est installé
  stat:
    path: "{{ lynis_path }}"
  register: lynis_installed
  tags:
    - lynis
    - validation

- name: Installer Lynis si nécessaire
  package:
    name: lynis
    state: present
  when: not lynis_installed.stat.exists
  tags:
    - lynis
    - critical

- name: Exécuter un audit système initial avec Lynis
  shell: "{{ lynis_command }} > {{ lynis_log_file }} 2>&1"
  register: lynis_output
  changed_when: false
  ignore_errors: true
  when: lynis_installed.stat.exists
  tags:
    - lynis
    - audit

- name: Enregistrer l'exécution de l'audit initial dans le log global
  lineinfile:
    path: /var/log/audit_execution.log
    create: yes
    line: "[{{ ansible_date_time.date }} {{ ansible_date_time.time }}] Audit initial Lynis exécuté avec succès."
  when: lynis_output.rc == 0
  tags:
    - lynis
    - logging

- name: Planifier un audit Lynis quotidien
  cron:
    name: "Audit de sécurité avec Lynis"
    user: root
    minute: "{{ lynis_cron_minute }}"
    hour: "{{ lynis_cron_hour }}"
    job: "{{ lynis_command }} --cronjob >> {{ lynis_history_log }} 2>&1 && echo '[`date`] Audit quotidien Lynis exécuté avec succès.' >> /var/log/audit_execution.log"
  tags:
    - cron
    - lynis
