---
# Rôle : yara-workflow
# ## Documentation des recommandations (CIS, ANSSI, DISA STIG)
#
# 🔹 CIS Benchmarks
# - **10.1** : S'assurer que des outils de détection de logiciels malveillants sont installés et activés.
# - **10.2** : Mettre à jour régulièrement les bases de signatures de logiciels malveillants.
# - **10.4** : Planifier des analyses régulières pour identifier les menaces.
# 👉 Référence : https://www.cisecurity.org/cis-benchmarks
#
# 🔹 ANSSI (Agence Nationale de la Sécurité des Systèmes d'Information)
# - **6.1.2** : Déployer des outils pour détecter des fichiers malveillants à l'aide de signatures connues.
# - **6.4.1** : Automatiser les analyses pour réduire les risques liés aux erreurs humaines.
# - **6.6.1** : Centraliser les règles et les rapports dans des répertoires sécurisés.
# 👉 Référence : https://www.ssi.gouv.fr/guide/
#
# 🔹 DISA STIG (Defense Information Systems Agency)
# - **V-230418** : Implémenter un système d’analyse automatisé pour détecter les logiciels malveillants.
# - **V-230419** : Planifier des analyses régulières des fichiers systèmes (cron ou autre).
# - **V-230420** : Maintenir les bases de signatures à jour pour garantir leur efficacité.
# 👉 Référence : https://public.cyber.mil/stigs/
#
# ## Fonctionnalités
# - Installation de YARA pour la détection des fichiers malveillants.
# - Gestion des règles YARA (fichier local inclus dans le rôle).
# - Planification des analyses régulières avec `cron`.
# - Centralisation des règles et des journaux dans des répertoires sécurisés.

# Installer les dépendances nécessaires
- name: Installer les dépendances pour YARA
  ansible.builtin.apt:
    name: "{{ yara_dependencies }}"
    state: present
  tags:
    - yara
    - dependencies

# Copier les règles YARA depuis le dossier du rôle
- name: Copier les règles YARA vers le répertoire cible
  ansible.builtin.copy:
    src: "rules/yara-rules-full.yar"
    dest: "{{ yara_rules_path }}/yara-rules-full.yar"
    owner: root
    group: root
    mode: "0644"
  tags:
    - yara
    - rules

# Vérifier les règles YARA
- name: Vérifier les règles YARA
  ansible.builtin.command:
    cmd: "yara -r {{ yara_rules_path }}/yara-rules-full.yar {{ yara_scan_target }}"
  register: yara_verify
  changed_when: false
  tags:
    - yara
    - verify

- name: Afficher les résultats de la vérification
  ansible.builtin.debug:
    var: yara_verify.stdout
  tags:
    - yara
    - verify

# Planifier une analyse automatique YARA
- name: Planifier une analyse YARA quotidienne
  ansible.builtin.cron:
    name: "Analyse quotidienne YARA"
    minute: "{{ yara_cron_minute }}"
    hour: "{{ yara_cron_hour }}"
    job: "yara -r {{ yara_rules_path }}/yara-rules-full.yar {{ yara_scan_target }} > /var/log/yara_scan.log 2>&1"
  tags:
    - yara
    - cron

# Exécuter une analyse YARA
- name: Exécuter une analyse YARA
  ansible.builtin.command:
    cmd: "yara -r {{ yara_rules_path }}/yara-rules-full.yar {{ yara_scan_target }}"
  register: yara_scan
  changed_when: false
  tags:
    - yara
    - scan

- name: Afficher les résultats de l'analyse
  ansible.builtin.debug:
    var: yara_scan.stdout
  tags:
    - yara
    - scan
