---
rsyslog_config:
  rotation_days: 14
  compression: true
  delay_compression: true
  log_files:
    - /var/log/auth.log
    - /var/log/sudo.log
    - /var/log/sshd_critical.log
    - /var/log/system_errors.log
    - /var/log/clamav/clamav.log
    - /var/log/audit/audit.log
    - /var/log/yara/yara_scan.log
  critical_logs:
    - name: "sudo"
      path: "/var/log/sudo.log"
    - name: "sshd"
      path: "/var/log/sshd_critical.log"
    - name: "system_errors"
      path: "/var/log/system_errors.log"
    - name: "clamav"
      path: "/var/log/clamav/clamav.log"
    - name: "auditd"
      path: "/var/log/audit/audit.log"
    - name: "yara"
      path: "/var/log/yara/yara_scan.log"
