---
  - name: Restart auditd
    ansible.builtin.service:
      name: auditd
      state: restarted

  - name: Restart journald
    ansible.builtin.service:
      name: systemd-journald
      state: restarted
