---
- name: Mettre à jour GRUB
  ansible.builtin.command:
    cmd: update-grub
  become: true

- name: Redémarrer auditd
  ansible.builtin.service:
    name: auditd
    state: restarted

- name: Redémarrer journald
  ansible.builtin.service:
    name: systemd-journald
    state: restarted
