---
# Activer UFW avec des règles par défaut (CIS 3.5.2, ANSSI R87)
- name: Activer UFW avec des règles par défaut
  ansible.builtin.ufw:
    state: enabled
    policy: deny
    direction: incoming
  notify: Recharger UFW
  tags:
    - firewall
    - critical

# Autoriser les connexions SSH via UFW (CIS 3.5.3, ANSSI R88)
- name: Autoriser les connexions SSH via UFW
  ansible.builtin.ufw:
    rule: allow
    port: "22"
    proto: "tcp"
  notify: Recharger UFW
  tags:
    - firewall
    - ssh
