---
- name: Durcissement CIS avec gestion des utilisateurs et services
  hosts: node1
  become: yes

  tasks:
    - name: ===== Début du playbook Durcissement CIS =====
      debug:
        msg: "Déploiement commencé : Durcissement CIS avec gestion des utilisateurs et services."

    # Installer les paquets nécessaires
    - include_role:
        name: packages
    - include_role:
        name: users
    - include_role:
        name: ufw
    - include_role:
        name: fail2ban

    # Gestion de la sécurité des mots de passe et de PAM
    - include_role:
        name: passwords
    - include_role:
        name: pam_faillock

    # Sécurisation du noyau et GRUB
    - include_role:
        name: kernel
    - include_role:
        name: grub-password

    # Surveillance et audit
    - include_role:
        name: aide
    - include_role:
        name: lynis
    - include_role:
        name: clamav
    - include_role:
        name: auditd
    - include_role:
        name: rsyslog

    # Rapport post-déploiement
    - include_role:
        name: post_deployment_report

    # Appliquer ssh-hardening en dernier
    - include_role:
        name: ssh-hardening # Rôle SSH durci en dernier

    - name: ===== Fin du playbook =====
      debug:
        msg: "Le déploiement du playbook est terminé avec succès !"
