---
# Redémarrer le service SSH après modification de la configuration
- name: Restart SSH service
  ansible.builtin.systemd:
    name: ssh
    state: restarted
  tags:
    - ssh
    - service-restart
